### ISSUE TITLE
Add code in download.py that downloads court_summary

### ISSUE THREAD

**Issue by itsamejoshab** [CodeForPhilly/pbf-scraping#37]
court_summary file provides a few key pieces of information. Right now download.py is only downloading the raw dockets and parsing them. we need to add the new code to download.py which will create a 2nd .csv file for the court summary data, and upload that into a new S3 bucket, with a new Athena table added to it.

**Comment by notchia** [comment]
I asked a clarifying question to this on Slack, but have a followup question. I understand why it's a hassle to add new data (sex + race from court summary) to an existing entry ( information from docket file). But otherwise, is there an advantage to having the two files separate? Since we will be retrieving the information from both files at the same time in `download.py`, it seems to me that it would streamline our analysis process down the line to merge the dictionaries containing the parsed court summary and docket data for a single docket number and return that as our entry for a docket. Then only a single .csv file is created, which has both the original docket info and sex+race already linked together to the same docket number.

**Comment by notchia** [comment]
I made a draft pull request to show what I mean. @itsamejoshab, I tried to add you as a reviewer but wasn't able to for some reason.
