### ISSUE TITLE
Parameterize download.py so it takes a docket number as an argument 

### ISSUE THREAD

**Issue by adamrlinder** [CodeForPhilly/pbf-scraping#55]
Since we'll need to use download.py to download and parse dockets and court summaries from the past, we need it to be able to take a docket number as an argument.

As a piggyback onto this request, it would be great if we could also make it so that download.py had support for CP dockets too. That's the only other choice in the first docket number dropdown on https://ujsportal.pacourts.us/DocketSheets/CP.aspx

<img width="402" alt="Screen Shot 2020-11-11 at 3 56 21 PM" src="https://user-images.githubusercontent.com/47930066/98863486-72ee8400-2436-11eb-9407-a6106b700026.png">

**Comment by notchia** [comment]
My understanding is that Common Pleas dockets for Philly-related cases will only exist if the case is moved from the Philly Municipal Court to CP, since MC has initial jurisdiction in processing every arrest in Philadelphia. Is this correct?

If so, would the purpose of downloading CP dockets be solely to find the outcome of a case that was originally processed by the MC? Then we'll later also need to find a way to pull the "cross-court docket number" from MC dockets to look up the CP docket with. Otherwise, what additional information is in the CP dockets that is relevant to PBF?

**Comment by hruday97** [comment]
Just saw the issue. The script download.py should be already downloading CP dockets. I even tried downloading dockets and it is working for me. By this week I will put a PR with proper comments for documentation of the download.py file.

**Comment by adamrlinder** [comment]
@notchia good question! That is how the CP dockets work. I _think_ it should be the case that we will always know the CP docket number that we want to download, so we don't need to worry about pulling the cross-court docket number from MC dockets (though I wouldn't complain if you were inspired and wrote up a way to pull that information out anyway ;) )

The use case I'm thinking of is that PBF often needs to pull down updated dockets for the clients that they've bailed out. While we're parameterizing it I wanted to see if it was quick and easy to add that functionality.

**Comment by notchia** [comment]
Okay! Then, like @hruday97 mentioned, `main` can already download and (in theory) parse CP dockets (it takes the whole 5-section docket number and drops those sections into the search box), so it's basically there already. I will probably also need to make some small changes to `parse_dockets.py` to make sure it works on CP dockets, since as far as I know we've only tested them on MC dockets so far.

**Comment by notchia** [comment]
To clarify: do we want to be able to run `download.py` as a script with an optional command line argument of a specific docket number (saving a CSV with the docket number in the name)? Or do we want a function that can take a docket number and return (or just save as a CSV) the parsed data?

**Comment by adamrlinder** [comment]
@notchia yes -- it should return a CSV with the name of the docket number. The parameterized version should also download the associated Court Summary and return a CSV for that as well.
